car_wash/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')),
    path('', include('user.urls'))
]

management/urls.py
from django.urls import path
from .views import homepage, car_washes, car_wash_detail, washers, order, cars, car_json


urlpatterns = [
    path('', homepage, name='homepage'),
    path('car_washes/', car_washes, name='car_washes'),
    path('car_washes/<int:cw_pk>/details', car_wash_detail, name='cw_detail'),
    path('car_washes/<int:cw_pk>/washers', washers, name='washers'),
    path('car_washes/<int:cw_pk>/cars', cars, name='cars'),
    path('order/<int:cw_pk>', order, name='order'),
    path('car_json/<int:cw_pk>', car_json, name='car_json')
]

user/urls.py
from django.urls import path
from .views import register, user_login, user_logout


urlpatterns = [
    path('logout/', user_logout, name='logout'),
    path('login/', user_login, name='login'),
    path('register/', register, name='register'),

]

management/models.py
from django.db import models
from management.choices import CAR_TYPES, PAYMENT_TYPES, ORGANIZATION_TYPES
from django.utils.translation import ugettext_lazy as _


class Location(models.Model):
    city = models.CharField(max_length=100)
    street_adress = models.CharField(max_length=100, unique=True)
    zip_code = models.CharField(max_length=10)

    class Meta:
        verbose_name = _('Location')
        verbose_name_plural = _('Locations')

    def __str__(self):
        return f"{self.city} | {self.street_adress}"


class CarWash(models.Model):
    full_name = models.CharField(max_length=50, unique=True)
    location = models.OneToOneField(to='management.Location',
                                    on_delete=models.PROTECT)
    organzation_type = models.IntegerField(choices=ORGANIZATION_TYPES)
    tax_id = models.CharField(max_length=10, unique=True)
    creation_time = models.DateTimeField()

    class Meta:
        verbose_name = _('Car wash')
        verbose_name_plural = _('Car washes')

    def __str__(self):
        return self.full_name


class Washer(models.Model):
    car_wash = models.ForeignKey(
        to='management.CarWash', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    personal_id = models.CharField(max_length=11, unique=True)
    payment = models.DecimalField(default=0, max_digits=6, decimal_places=2)

    class Meta:
        ordering = ['last_name']
        verbose_name = _('Washer')
        verbose_name_plural = _('Washers')

    def __str__(self):
        return f"{self.last_name} {self.first_name} | {self.car_wash}"


class CarType(models.Model):
    car_wash = models.ForeignKey(
        to='management.CarWash', on_delete=models.CASCADE)
    type = models.IntegerField(choices=CAR_TYPES)
    price = models.DecimalField(max_digits=4, decimal_places=2)

    class Meta:
        verbose_name = _('Car type')
        verbose_name_plural = _('Car types')

    def __str__(self):
        return f"{CAR_TYPES[self.type-1][1]} | {self.car_wash.full_name}"


class Car(models.Model):
    car_type = models.ForeignKey(
        to='management.CarType', on_delete=models.PROTECT)
    license_plate = models.CharField(max_length=30)

    class Meta:
        verbose_name = _('Car')
        verbose_name_plural = _('Cars')

    def __str__(self):
        return f"{self.license_plate} | {self.car_type}"


class Order(models.Model):
    washer = models.ForeignKey(
        to='management.Washer', on_delete=models.PROTECT)
    car = models.ForeignKey(to='management.Car', on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    payment_type = models.IntegerField(choices=PAYMENT_TYPES)  # for decoration
    created = models.DateTimeField(auto_now_add=True)
    finish_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        if self.finish_time:
            return f"Finished at: {self.finish_time} | {self.car.license_plate}"
        else:
            return f"{'Not finished yet'} | {self.car.license_plate}"

    def save(self, *args, **kwargs):
        self.price = self.car.car_type.price
        if self.finish_time:
            self.washer.payment += round(self.car.car_type.price / 2, 2)
            self.washer.save()
        super(Order, self).save(*args, **kwargs)

management/forms.py
from django.forms import ModelForm
from management.choices import PAYMENT_TYPES
from .models import Car, CarType, Order, Washer
from django.forms import ModelChoiceField, TypedChoiceField, CharField
from django.core.validators import MinLengthValidator


class CarForm(ModelForm):
    car_type = ModelChoiceField(empty_label='Choose the car type', queryset=None)
    license_plate = CharField(validators=[MinLengthValidator(6)])

    class Meta:
        model = Car
        fields = '__all__'

    def __init__(self, cw_pk=None, **kwargs):
        super(CarForm, self).__init__(**kwargs)
        self.fields['car_type'].queryset = CarType.objects.filter(car_wash_id=cw_pk)


class OrderForm(ModelForm):
    washer = ModelChoiceField(empty_label='Choose the washer', queryset=None)
    payment_type = TypedChoiceField(choices=PAYMENT_TYPES)

    class Meta:
        model = Order
        fields = ('washer', 'payment_type')

    def __init__(self, cw_pk=None, **kwargs):
        super(OrderForm, self).__init__(**kwargs)
        # self.fields['car'].queryset = Car.objects.filter(car_type__car_wash_id=cw_pk)
        self.fields['washer'].queryset = Washer.objects.filter(car_wash_id=cw_pk)

management/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from decimal import Decimal
from django.db.models import Sum, Count, Q, F, ExpressionWrapper, DecimalField
from django.shortcuts import get_object_or_404
from django.utils import timezone
from .models import CarWash, Order, Car
from .forms import CarForm, OrderForm
from django.contrib import messages
from .utils import my_paginator


def homepage(request):
    return render(request, 'management/homepage.html')


def car_washes(request):
    car_washes = CarWash.objects.all()
    return render(request, 'management/car_washes.html',
                  context={'car_washes': car_washes}
                  )


def car_wash_detail(request, cw_pk):
    car_wash = get_object_or_404(CarWash, pk=cw_pk)
    # washed_cars = car_wash.washer_set.annotate(
    #     orders_count=Count('order', filter=Q(order__finish_time__isnull=False)),
    # ).aggregate(Sum('orders_count'))['orders_count__sum']
    washed_cars = Order.objects.filter(finish_time__isnull=False,
                                       washer__car_wash_id=car_wash.id).count()
    washed_cars = washed_cars if washed_cars else 0
    return render(request, 'management/car_wash_detail.html',
                  context={'car_wash': car_wash,
                           'washed_cars': washed_cars}
                  )


def washers(request, cw_pk):
    car_wash = get_object_or_404(CarWash, pk=cw_pk)

    washers = car_wash.washer_set.annotate(
        washer_earned_money=ExpressionWrapper(
            F('order__price')/Decimal('2.00'), output_field=DecimalField())
    ).annotate(
        all_washed=Count('order', filter=Q(order__finish_time__isnull=False)),

        all_pay=Sum('washer_earned_money', filter=Q(order__finish_time__isnull=False)),

        yearly_washed=Count('order', filter=Q(
            order__finish_time__gte=timezone.now() - timezone.timedelta(days=356))),

        yearly_pay=Sum('washer_earned_money', filter=Q(
            order__finish_time__gte=timezone.now() - timezone.timedelta(days=365))),

        monthly_washed=Count('order', filter=Q(
            order__finish_time__gte=timezone.now() - timezone.timedelta(days=30))),

        monthly_pay=Sum('washer_earned_money', filter=Q(
            order__finish_time__gte=timezone.now() - timezone.timedelta(days=30))),

        weekly_washed=Count('order', filter=Q(
            order__finish_time__gte=timezone.now() - timezone.timedelta(days=7))),

        weekly_pay=Sum('washer_earned_money', filter=Q(
            order__finish_time__gte=timezone.now() - timezone.timedelta(days=7))),
    )

    return render(request, 'management/washers.html',
                  context={'washers': washers, }
                  )


def cars(request, cw_pk):
    car_wash = get_object_or_404(CarWash, pk=cw_pk)
    car_form = CarForm(car_wash.id)
    searched_count = None
    page = request.GET.get('page', 1)
    q = request.GET.get('q', None)
    if q:
        car_list = Car.objects.filter(
            Q(car_type__car_wash_id=car_wash.id) & Q(license_plate__icontains=q)
        )
        searched_count = car_list.count()
    else:
        car_list = Car.objects.filter(car_type__car_wash_id=car_wash.id)

    if request.method == 'POST':
        car_form = CarForm(car_wash.id, data=request.POST)
        if car_form.is_valid():
            car_form.save()
            car_form = CarForm(car_wash.id)
            messages.success(request, 'The operation was successful!')
    return render(request, 'management/cars.html',
                  context={'cars': my_paginator(page, car_list, 8),
                           'form': car_form,
                           'searched_count': searched_count,
                           })


def order(request, cw_pk):
    car_wash = get_object_or_404(CarWash, pk=cw_pk)
    order_form = OrderForm(car_wash.id)
    if request.method == 'POST':
        order_form = OrderForm(car_wash.id, data=request.POST)
        car = Car.objects.filter(
            Q(car_type__car_wash_id=car_wash.id) & Q(license_plate=request.POST['car'])).first()
        if not car:
            messages.error(
                request, "Car with given license plate couldn't be found!")
        elif order_form.is_valid():
            car_form = order_form.save(commit=False)
            car_form.car = car
            car_form.save()
            order_form = OrderForm(car_wash.id)
            messages.success(request, 'The operation was successful!')
    return render(request, 'management/order.html',
                  context={'car_wash': car_wash,
                           'form': order_form})


def car_json(request, cw_pk):
    if request.method == 'POST':
        data = Car.objects.filter(car_type__car_wash_id=cw_pk).values_list(
            'license_plate', flat=True)
        return JsonResponse(list(data), safe=False)
    return HttpResponse(status=404)

templates/management/car_wash_detail.html
{% extends "base.html" %}

{% block content %}
<ul class="collection with-header">
    <li class="collection-header center-align">
        <h4>{{car_wash.full_name}}</h4>
    </li>
    <li class="collection-item center-align">Location
        <ul>
            <li>City: {{car_wash.location.city}}</li>
            <li>Street: {{car_wash.location.street_adress}}</li>
            <li>Zip Code: {{car_wash.location.zip_code}}</li>
        </ul>
    </li>
    <li class="collection-item center-align">Tax id: {{car_wash.tax_id}}</li>
    <li class="collection-item center-align">Company creation time: {{car_wash.creation_time|date:'M d Y'|upper}}</li>

</ul>

<h4 class='center-align'>Company totally washed {{washed_cars}} car{{washed_cars|pluralize}}</h4>

{% endblock %}

templates/management/car_washes.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if request.GET.order != 'True' %}
<div class='container'>
    {% for car_wash in car_washes%}
    {% if forloop.counter0|divisibleby:"2" %}
    <div class="row">
        {% endif %}
        <div class="col s12 m6">
            <div class="card red darken-4">
                <div class="card-content white-text">
                    <span class="card-title">{{car_wash.full_name}}</span>
                    <p>{% lorem 30 w %}</p>
                </div>
                <div class="card-action">
                    <a class="black-text" href="{% url 'cw_detail' car_wash.id %}">Get More Details</a>
                    <a class="black-text" href="{% url 'washers' car_wash.id %}">Washers</a>
                    <a class="black-text" href="{% url 'cars' car_wash.id %}">Cars</a>
                </div>
            </div>
        </div>

        {% if forloop.counter|divisibleby:"2" or forloop.last %}
    </div>
    {% endif %}
    {% endfor %}
</div>
{% else %}
<div class='container'>
    <div>
        <h4 class="center-align">Please Choose Company</h5>
    </div>

    {% for car_wash in car_washes%}
    {% if forloop.counter0|divisibleby:"2" %}
    <div class="row">
        {% endif %}
        <div class="col s12 m6">
            <div class="card">
                <div class="card-image">
                    <a href="{% url 'order' car_wash.id %}">
                        <img src="{% static 'images/car_wash1.jpeg' %}" width="200" height="200">
                    </a>
                    <span class="card-title green-text">{{car_wash.full_name}}</span>
                </div>
                <div class="card-content">
                    <p><strong>{{car_wash.location}}</strong></p>
                    <p>{% lorem 30 w %}</p>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:"2" or forloop.last %}
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endif %}

{% endblock %}

templates/management/cars.html
{% extends "base.html"%}


{% block content %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            {% if messages %}
            {% for message in messages %}
            <h4{% if message.tags %} class="{{ message.tags }} center-align green-text" {% endif %}>
                <strong> {{ message }} </strong>
                </h4>
                {% endfor %}
                {% else %}
                <div>
                    <h4 class="center-align">Create your car here</h5>
                </div>
                {% endif %}
                <strong class="center-align">{{form.errors}}</strong>
                <div class="input-field col s6 ">
                    {{form.car_type}}
                    <label>Car Type</label>
                </div>
                <div class="input-field col s6 ">
                    {{form.license_plate}}
                    <label for="id_license_plate">License Plate</label>
                </div>
                <div class="center">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Submit
                    </button>
                </div>
        </div>
    </form>
    <form action="" method="get">
        <div class="row">
            <div class="input-field col s4 offset-s4">
                <input id="search_input" type="search" class="validate" name="q">
                <label for="search_input"><i class="material-icons">search</i>
                    <label for="search_input">Search by license plate</label>
            </div>
        </div>
        <div class="row">
            <div class="center">
                <button class="btn waves-effect waves-light" type="submit">
                    Search
                </button>
            </div>
        </div>
        <div class="row">
            {% if searched_count %}
            <p>{{searched_count}} result{{searched_count|pluralize}} found
            <p>
                {% elif searched_count == 0 %}
            <p>No results found</p>
            {% endif %}
        </div>
    </form>
    {% for car in cars %}
    {% if forloop.counter0|divisibleby:"4" %}
    <div class="row">
        {% endif %}
        <div class="col s6 m3">
            <div class="card red darken-4">
                <div class="card-content white-text">
                    <span class="card-title">{{car}}</span>
                    <p>{% lorem 10 w %}</p>
                </div>
                <div class="card-action center">
                    <a class="black-text" href="#">Get More Details</a>
                </div>
            </div>
        </div>

        {% if forloop.counter|divisibleby:"4" or forloop.last %}
    </div>
    {% endif %}
    {% endfor %}
    <ul class="pagination">
        {% if cars.has_previous %}
        <li class="waves-effect"><a href="?page={{ cars.previous_page_number }}&q={{request.GET.q}}"><i class="material-icons">chevron_left</i></a></li>
        {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
        {% endif %}
        {% for i in cars.paginator.page_range %}
        {% if cars.number == i %}
        <li class="active"><a>{{ i }}</a></li>
        {% else %}
        <li class="waves-effect"><a href="?page={{ i }}&q={{request.GET.q}}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if cars.has_next %}
        <li class="waves-effect"><a href="?page={{ cars.paginator.num_pages }}&q={{request.GET.q}}"><i class="material-icons">chevron_right</i></a></li>
        {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
        {% endif %}
    </ul>
</div>

{% endblock %}

templates/management/homepage.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class='padd'>
        <div class='align center'>
            <form action="{% url 'car_washes' %}" method='get'>
                <input type="hidden" value="True" name="order">
                <input type="submit" class="btn-large" value="Order Now">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m12">
            <div class="card yellow darken-2">
                <div class="card-content black-text">
                    <span class="card-title">Car Washes</span>
                    <p>{% lorem 50 w %}</p>
                </div>
                <div class="card-action center-align">
                    <a class="green-text" href="{% url 'car_washes' %}">Get more details</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/management/order.html
{% extends "base.html" %}

{% load static %}


{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            {% if messages %}
            {% for message in messages %}
            <h4{% if message.tags == 'error' %} class="{{ message.tags }} center-align red-text" {% elif message.tags == 'success' %} class="{{ message.tags }} center-align green-text" {% endif %}>
                <strong> {{ message }} </strong>
                </h4>
                {% endfor %}
                {% else %}
                <div>
                    <h4 class="center-align">Place the order</h5>
                </div>
                {% endif %}
                <div class="input-field col s12 ">
                    <p>
                        <label for="car_license_plate">Choose the car</label>
                        <input name='car' placeholder="Car license plate" id="car_license_plate" type="text" class="validate">
                    </p>
                    <p>{{form.washer}}</p>
                    {{form.errors.washer}}
                    <p>{{form.payment_type}}</p>
                    {{form.errors.payment_type}}
                    <div class="center">
                        <button class="btn waves-effect waves-light" type="submit" name="action">
                            Submit
                        </button>
                    </div>
                </div>
        </div>
    </div>
</form>

<script>
    var endpoint = '/car_json/{{car_wash.id}}';
    $.ajax({
        method: "POST",
        url: endpoint,
        data: {
            'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
        },
        success: function(src) {
            $("#car_license_plate").autocomplete({
                source: function(request, response) {
                    var results = $.ui.autocomplete.filter(src, request.term);

                    response(results.slice(0, 10));
                }
            });
        },
        error: function(error_data) {
            console.log(error_data);
        }
    });
</script>


{% endblock %}

templates/management/washers.html
{% extends "base.html" %}
{% load index %}

{% block content %}

<style>
    #personal_info {
        font-size: 20px;
        font-weight: bold;
    }
</style>


<div class='container'>
    {% for washer in washers %}
    {% if forloop.counter0|divisibleby:"2" %}
    <div class='row'>
        {% endif %}
        <div class='col s12 m6'>
            <div class="card">
                <div class="card-content">
                    <ul class='center-align'>
                        <li id='personal_info'>{{washer.last_name}}</li>
                        <li id='personal_info'>{{washer.first_name}}</li>
                    </ul>
                    <p>{% lorem 29 w %}</p>
                </div>
                <div class="card-tabs">
                    <ul class="tabs tabs-fixed-width">
                        <li class="tab"><a href="#weakly{{washer.id}}">Weakly</a></li>
                        <li class="tab"><a href="#monthly{{washer.id}}">Monthly</a></li>
                        <li class="tab"><a href="#yearly{{washer.id}}">Yearly</a></li>
                        <li class="tab"><a href="#default{{washer.id}}">Default</a></li>
                    </ul>
                </div>
                <div class="card-content grey lighten-4">
                    <div id="weakly{{washer.id}}">
                        <ul>
                            <li>Washed {{washer.weekly_washed|default_if_none:0}} car{{washer.weekly_washed|pluralize}}</li>
                            <li>Earned ₾{{washer.weekly_pay|default_if_none:0}}</li>
                        </ul>
                    </div>
                    <div id="monthly{{washer.id}}">
                        <ul>
                            <li>Washed {{washer.monthly_washed|default_if_none:0}} car{{washer.monthly_washed|pluralize}}</li>
                            <li>Earned ₾{{washer.monthly_pay|default_if_none:0}}</li>
                        </ul>
                    </div>
                    <div id="yearly{{washer.id}}">
                        <ul>
                            <li>Washed {{washer.yearly_washed|default_if_none:0}} car{{washer.yearly_washed|pluralize}}</li>
                            <li>Earned ₾{{washer.yearly_pay|default_if_none:0}}</li>
                        </ul>
                    </div>
                    <div id="default{{washer.id}}">
                        <ul>
                            <li>Washed {{washer.all_washed|default_if_none:0}} car{{washer.all_washed|pluralize}}</li>
                            <li>Earned ₾{{washer.all_pay|default_if_none:0}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:"2" or forloop.last %}
    </div>
    {% endif %}
    {% endfor %}
</div>
<script>
    M.AutoInit();
</script>

{% endblock %}